talk:
  isLive: False
  speaker: Irina Rish

donations:
  paypal_url: https://www.paypal.com/donate?campaign_id=RV9EZH4UPSA5A
  spreadsheetURL: https://docs.google.com/spreadsheets/d/e/2PACX-1vTXKpZ8iB5Nz6mHl5iYUAA68DU1D-gCnwuDREnVULI9JrOnh1CF8U1RF6zDbVfrkw/pub?gid=1443797343&single=true&output=csv
  target: 1000000
  targetText: "1,000,000"
